# FROM php:8.3.2-cli

# RUN curl -sS https://getcomposer.org/installer | php -- \
#      --install-dir=/usr/local/bin --filename=composer

# COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# RUN apt-get update && apt-get install -y zlib1g-dev \
#     libzip-dev \
#     unzip

# RUN docker-php-ext-install pdo pdo_mysql sockets zip

# RUN mkdir /app

# COPY . /app

# WORKDIR /app

# #Workaround for composer not being able to run as root
# ENV COMPOSER_ALLOW_SUPERUSER=1

# CHOWN  -R www-data:www-data /app


# # RUN composer diagnose

# RUN composer install

# # #Run test for php
# # RUN php artisan test
# # RUN php artisan migrate:refresh --seed

# CMD php artisan serve --host=0.0.0.0 --port=8000

# EXPOSE 8000

FROM php:8.3-fpm


COPY ./ ./
RUN rm -rf vendor

RUN apt-get update -y && apt-get upgrade -y && apt-get autoremove -y && apt-get autoclean -y

# Install docker-php-extension-installer to make our lives easier with installing php extensions.
COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/local/bin/
RUN install-php-extensions @composer-2.2.4
RUN install-php-extensions pdo_mysql sockets zip

# Create folders required by Laravel
RUN mkdir -p bootstrap/cache storage/app storage/framework/cache storage/framework/sessions storage/framework/views \
    storage/logs secrets \
    && chown -R www-data /var/www /var/www/html \
    && composer install --ignore-platform-reqs \
    && php artisan storage:link \
    && rm -rf docker

USER www-data
VOLUME /var/www/html/storage
WORKDIR /var/www/html

EXPOSE 9000
