FROM node:18.16.0 as build-stage

WORKDIR /app

COPY . .
RUN npm install
RUN npm run build



FROM nginx:alpine


WORKDIR /var/www/html/public
COPY --from=build-stage ./app/public /var/www/html/public

COPY ./docker/nginx/app.conf /etc/nginx/conf.d/app.conf
RUN mkdir -p /storage/app/public \
    && touch /storage/app/public/.ignore \
    && ln -s /storage/app/public storage

EXPOSE 80

