name: laravel

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up Docker
        run: |
          sudo for pkg in docker.io docker-doc docker-compose docker-compose-v2 podman-docker containerd runc; do sudo apt-get remove $pkg; done
          # sudo apt-get remove docker docker-engine docker.io containerd runc
          # sudo apt-get purge docker-ce docker-ce-cli containerd.io docker-compose-plugin docker-compose
          # sudo rm -rf /etc/bash_completion.d/docker /usr/local/bin/docker-compose /etc/bash_completion.d/docker-compose
          sudo apt-get update
          sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

      - name: Log in to Docker Hub (if needed)
        run: |
          # Add your Docker Hub login steps here if you're pushing images

      - name: Build and run Docker Compose
        run: |
          bash build.sh

      # Add other steps as needed (e.g., testing, deployment, etc.)
