name: laravel

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      # - name: Set up Docker
      #   run: |
      #     bash docker-setup.sh

      # - name: Set up php environment
      #   run: |
      #     bash php-setup.sh

      # - name: Log in to Docker Hub (if needed)
      #   run: |
      #     # Add your Docker Hub login steps here if you're pushing images

      - name: Build and run Docker Compose
        run: |
          bash build.sh

      # Add other steps as needed (e.g., testing, deployment, etc.)
